### ISSUE TITLE
Crashing on creating new world on forge server

### ISSUE THREAD

**Issue by JadeFalcon** [dadobug1111/DadobugOres#1]
Dadobug Ores v. 1.0.2
Moonlight Lib v. 2.2.35
[crash-2023-06-02_12.08.31-fml.txt](https://github.com/dadobug1111/DadobugOres/files/11639957/crash-2023-06-02_12.08.31-fml.txt)

**Comment by dadobug1111** [comment]
Just fixed in 1.0.3! Curseforge should approve file soon. Apparently I was loading clientside data in dedicated server mode.

**Comment by JadeFalcon** [comment]
[crash-2023-06-06_15.51.40-fml.txt](https://github.com/dadobug1111/DadobugOres/files/11670887/crash-2023-06-06_15.51.40-fml.txt)
It still seems to be crashing for me, I'm not sure if this is a different issue or not

**Comment by dadobug1111** [comment]
It seems I made it load clientside resources when _not_ clientside, instead of only clientside. 1.0.4 should be on curseforge soon.
