### ISSUE TITLE
No drops on the forge version

### ISSUE THREAD

**Issue by ElRichiRicon** [dadobug1111/DadobugOres#2]
Tried TNT and tried netherite pickaxe with efficiency V. No drops from either bedrock nor dense ores. Some ores drop only xp orbs, like the lapis one.
Fluid ores do work.

latest.log: https://pastebin.com/UGu7S6bi

**Comment by dadobug1111** [comment]
temp fix: downgrade moonlight.

Working on bugfix.

**Comment by dadobug1111** [comment]
should be fixed as of 1.0.5
